// Replace these examples with your projects. model: './models/example.glb'
// accepts a self-contained, uncompressed GLB; null uses a procedural placeholder.
export const projects = [
  { id: 'project-01', title: 'Hermite-Gaussian Phased Array Atenna', category: 'RF & ELECTROMAGNETICS', color: '#d6ef75', shape: 'array', model: null,
    summary: 'An exploration of how individual elements become a coordinated system.',
    tags: ['RF design', 'Simulation', 'Prototyping'],
    overview: 'This is a sample project entry. Use this space to describe the problem, why it mattered, and what you set out to build.',
    approach: 'Add your design decisions, simulation workflow, and the tradeoffs that shaped the result.',
    next: 'Replace the illustrative array with your CAD model, then add measurements and lessons learned.' },
  { id: 'project-02', title: 'Precision motion', category: 'MECHANICAL SYSTEMS', color: '#a6c9fa', shape: 'motion', model: null,
    summary: 'Turning a mechanical idea into controlled, repeatable movement.',
    tags: ['Mechanical design', 'Motion control', 'CAD'],
    overview: 'This sample entry is a place for a machine, fixture, or motion-system project. Describe what it needs to do and the constraints that make the design interesting.',
    approach: 'Document the mechanism, component selection, tolerances, and control strategy here.',
    next: 'Add the real assembly and a short account of how it performed against the original requirements.' },
  { id: 'project-03', title: 'Embedded control', category: 'ELECTRONICS & SOFTWARE', color: '#eea67d', shape: 'board', model: null,
    summary: 'Hardware and software working together to make a useful little system.',
    tags: ['PCB design', 'Firmware', 'Integration'],
    overview: 'This is an illustrative electronics project, ready for your own description. Explain the behavior you wanted and how the hardware and firmware deliver it.',
    approach: 'Add the architecture, key interfaces, and the choices you made for reliability and usability.',
    next: 'Replace the placeholder PCB with your exported model and summarize your test results.' },
  { id: 'project-04', title: 'Optical study', category: 'OPTICS & PRODUCT DESIGN', color: '#c8acf1', shape: 'optic', model: null,
    summary: 'An experiment in light, geometry, and the details of a physical object.',
    tags: ['Optics', 'Product design', 'Experimentation'],
    overview: 'Use this sample entry for an optical experiment or product concept. Describe the idea and the physical principles behind it.',
    approach: 'Explain your material choices, optical path, and the experiments used to test the concept.',
    next: 'Add your actual model, prototype photographs, and what the experiments revealed.' },
  { id: 'project-05', title: 'Structural form', category: 'DESIGN & FABRICATION', color: '#83d2c3', shape: 'structure', model: null,
    summary: 'A study in making a simple structure practical, precise, and buildable.',
    tags: ['Fabrication', 'Assembly design', 'Prototyping'],
    overview: 'This is a sample fabrication project. Introduce the object, its intended use, and the manufacturing constraints that informed the design.',
    approach: 'Describe how parts connect, how they are made, and what you changed between iterations.',
    next: 'Replace this model with the finished design and add the assembly process and final outcome.' }
];
